[build]
  command = 'pnpm build'

[[redirects]]
  from = "/"
  to = "/uk"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["uk"], Country = ["UA"], Role = ["admin"]}
